# -*- coding:utf-8 -*-

STDCARFIXRECORDFIELD = {
    'plateNo': '车牌号码',
    'engineNo': '发动机号码',
    'statementNo': '结算清单编号',
    'settlementDate': '结算日期',
    'deliveryDate': '送修日期',
    'deliveryMileage': '送修里程',
    'description': '故障信息',
    'repairItems': '维修项目列表',
    'repairParts': '维修配件列表',
    'others': '其他费用列表',
    'sum': '总费用',
    'QAInfo': '质保信息',
    'VINCode': 'VIN码',
    'vehicleOwner': '车辆所有者',
    'vehicleBrand': '车辆品牌',
    'vehicleType': '车辆类型',
    'repairType': '维修类型',
    'repairName': '送修人名称',
    'repairMobile': '送修人联系方式',
    'source': '维修表单来源',
    'status': '维修表单是否同步',
    'integratedRate': '表单完整率',
    'companyId': '维修企业',
    'xlsxPath': ' XLSX文件下载',
    'originalXLSXName': '原xlsx名称',
    'xlsxStatus': '数据标准化',
    'factoryDate': '出厂日期',
    'factoryMileage': '出厂里程',
    'updated': '更新日期',
    'created': '创建日期',
    'is_status_fix': '非标准数据',
    'store': '关联对应门店',
}
